import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import Nav from "react-bootstrap/Nav";

import logo from "../public/pbits.png";

export const Header = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>PBITS</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pbits.ico" />
      </Head>

      <Navbar
        className="sticky-top container-fluid"
        bg="dark"
        variant="dark"
        expand="lg"
      >
        <Navbar.Brand style={{ width: "6vw", padding: "0px" }}>
          <Image src={logo} alt="PBITS" />
        </Navbar.Brand>
        <Navbar.Toggle
          className="navbar-toggler-right"
          aria-controls="basic-navbar-nav"
        />

        <Navbar.Collapse id="basic-navbar-nav">
          <Nav>
            <Link href="#services" passHref>
              <a
                className={
                  router.pathname.includes("services")
                    ? "nav-item nav-link  text-primary"
                    : "nav-item nav-link"
                }
              >
                services
              </a>
            </Link>

            <Link href="#contact" className="nav-item nav-link" passHref>
              <a
                className={
                  router.pathname.includes("contact")
                    ? "nav-item nav-link  text-primary"
                    : "nav-item nav-link"
                }
              >
                contact
              </a>
            </Link>

            <Link href="#about" className="nav-item nav-link" passHref>
              <a
                className={
                  router.pathname.includes("#about")
                    ? "nav-item nav-link  text-primary"
                    : "nav-item nav-link"
                }
              >
                about
              </a>
            </Link>
          </Nav>
        </Navbar.Collapse>
      </Navbar>
    </>
  );
};
